powerdata=read.table("household_power_consumption.txt",header=TRUE,nrows=70000,sep=";",stringsAsFactors=FALSE,colClasses=c(NA,NA,rep("numeric",7)),na.strings="?")
plotdata = subset(powerdata,Date=="1/2/2007" | Date == "2/2/2007")
plotdata$DateTime=paste(plotdata$Date,plotdata$Time)
plotdata$DateTime =as.POSIXct(plotdata$DateTime,format="%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480, units="px")
plot(cdata$DateTime,cdata$Sub_metering_1,ylab="Energy Sub Metering",xlab="",col="black",type="l")
lines(cdata$DateTime,cdata$Sub_metering_2,col="red",type="l")
lines(cdata$DateTime,cdata$Sub_metering_3,col="blue",type="l")
legend("topright",lty=1,bty="n",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()